[IMP] Migrating product_label_report from rml to qweb (#96)
* [ADD] product_label_report: migrating to qweb reports large, medium, small size

[REF] product_label_repot: modifying doc.name in product_report

[REF] product_label_report: Adding README file

[FIX] product_label_report: Adding elements of form to the module.

- Cleanup __init__ files
- Indent properly rst on description in __openerp__.py

[FIX] product_label_report: product_report paper report names and ident in __openerp__ and __init__

[FIX] product_label_report: name redundant in product_report.xml

[FIX] product_label_report: disable error C8101

* [REF] product_label_report: Adding i18n es.po file

* [REF] product_label_report: Leaving empty es_MX.po

* [REF] typ_stock: Moving from product_label_report to typ_stock

* [REF] typ_stock: Modifing report name and add into __openerp__ file

* [REF] typ_stock: Change report name

* [REF] typ_stock: Setting label format

* [REF] typ_stock: Setting format

* [REF] typ_stock: view format